/* @generated by codegen/gen_widget.py - do not edit. */
#ifndef THERMIQ_WIDGET_GEN_H
#define THERMIQ_WIDGET_GEN_H

/* Sizes the caller's state array; equals WIDGET_ENTITY_COUNT. */
#define WIDGET_ENTITY_MAX 28

#endif /* THERMIQ_WIDGET_GEN_H */
